spring.datasource.url=jdbc:mysql://localhost:3306/academic_erp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ayush@123

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

# JWT
app.jwt.secret=AcademicErpSecretKeyForJwtToken123456789
app.jwt.expiration=86400000