package com.ayush.academicerp.utils;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class HeaderFooterPageEvent extends PdfPageEventHelper {

    PdfTemplate total;
    Font font = FontFactory.getFont(FontFactory.HELVETICA, 9);

    DateTimeFormatter formatter =
            DateTimeFormatter.ofPattern("dd MMM yyyy");

    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {
        total = writer.getDirectContent().createTemplate(30, 16);
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {

        PdfContentByte cb = writer.getDirectContent();

        float tableWidth = document.right() - document.left();

        PdfPTable header = new PdfPTable(3);

        try {
            header.setWidths(new int[]{2, 4, 2});
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        header.setTotalWidth(tableWidth);
        header.setLockedWidth(true);

        PdfPCell left = new PdfPCell(new Phrase(
                "University Institute of Engineering", font));
        left.setBorder(Rectangle.NO_BORDER);

        PdfPCell center = new PdfPCell(new Phrase(
                "Student Examination Eligibility Report", font));
        center.setBorder(Rectangle.NO_BORDER);
        center.setHorizontalAlignment(Element.ALIGN_CENTER);

        PdfPCell right = new PdfPCell(new Phrase(
                "Report Date: " + LocalDate.now().format(formatter), font));
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);

        header.addCell(left);
        header.addCell(center);
        header.addCell(right);

        header.writeSelectedRows(
                0,
                -1,
                document.left(),
                document.getPageSize().getHeight() - 20,
                writer.getDirectContent()
        );

        // FOOTER
        Phrase footer = new Phrase(
                "Generated by Academic ERP | Page "
                        + writer.getPageNumber() + " of ",
                font);

        float centerPos = (document.right() + document.left()) / 2;

        ColumnText.showTextAligned(
                cb,
                Element.ALIGN_CENTER,
                footer,
                centerPos,
                document.bottom() - 20,
                0
        );

        cb.addTemplate(
                total,
                centerPos + 55,
                document.bottom() - 20
        );
    }

    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {

        int totalPages = writer.getPageNumber();

        ColumnText.showTextAligned(
                total,
                Element.ALIGN_LEFT,
                new Phrase(String.valueOf(totalPages), font),
                2,
                2,
                0
        );
    }
}